### PR TITLE
Reformart script to use zigbee nwk source destination instead of route records

### PR DESCRIPTION
**Pull request by phe-sto**

### CODE REVIEW

**Comment by mingqian** [comment]
In a mesh, we cannot assume src and dst directly linked as they may be distant by several hops. Analyzing Route Record is way to find the route and thus the links we are going to draw.
What do you think?

**Comment by phe-sto** [comment]
Indeed this reveals a Zigbee link not a 802.15.4 link.
The route record is indeed a cleaver way to trace the 802.15.4 hops but when decrypting I face the issue where a frame from another PAN ID (and therefore another network key) was decrypted and the first byte was 5 so the script wrongly assumed this was a route record when this was in fact only gibberish.
What about tracing the source and destination of the 802.15.4 layer? 
I can understand that you could argue that your PCAP only contains the Zigbee traffic only of a single PAN ID (single key). But in real life it requires to filter the PCAP before using this script. Is it how you use this script? I which this (important, from my point of view) limitation could be highlighted in the README.

**Comment by mingqian** [comment]
Agree @phe-sto , yes I passed only a single pan to the script. I think the script can be improved by: 1. generate several .json for different pans 2. let the keyfile can contain multiple keys 3. smartly follow the tclk to fetch the new key.  Let me try on it.

**Comment by mingqian** [comment]
1,2 are done with commit f8d31f5. Still some problems with 3.

**Pull request closed without merging**
